### ISSUE TITLE
Selecting the Sequential or Hybrid presets does not always apply the implied neighbour values

### ISSUE THREAD

**Issue by TeoSkyBlue** [MircoWerner/ReSTIR-SSS#5]
If one were to first change the neighbour number and select one of the presets afterwards, on the first button press the old variables will be used.
Ex: Open program -> Change first and second passes' neighbours to just 1 -> Select either the Hybrid or Sequential preset (now 1 is being used for both passes, even though GUI has updated) -> Select either preset again(now neighbour values are properly applied). 
The following video showcases this behaviour, notice that the time taken for 1+1 neighbour on Sequential Shift stays the same even after the preset, which is 2 + 2 and more taxing, is applied.

![Seq_Shift_Button_fails](https://github.com/user-attachments/assets/3cbb772e-e02e-4f29-9478-17830f540d38)

**Comment by MircoWerner** [comment]
Fixed in db3f906c5a4219c1eccff4f9836b6476b5cf8f41. Thanks for reporting!
